@add.(库名称，像是Python里面的import，不用括号，和Python库兼容)

print("打印内容")

#( 我是一个注释 )#
// 我也是注释

var a = 1
#( 定义a变量=1 )#

time a = hour
#( 定义a变量=当前小时)

a = timer.计时器名称
#( 定义a变量为计时器 )#

set timer.计时器名称 minute
#( 添加一个计时器，单位为分钟 )#

a = 1 + 1
#( 定义a=1+1，-，*，/同理 )#

st function.a(b):
    print(b)
#( 定义函数a为打印b )#

f.a(123)
#( 调用函数a，且b值为123 )#

if a = 2:
    print("Hello World")
    #( 如果a=2则打印Hello World )#
elif a = 3:
    print(a)
    #( 如果a=3打印a )#
else:
    print("123")
    #( 如果不成立，打印123 )#

input(a)
#( 显示a，并且请求输入 )#

b=input(a)
#( 显示a，并且请求输入b的值 )#

key.如果 = if
#( 定义如果的效果等同于if )#
如果 1 = 1
#( 直接调用定义的key )#

exit
#( 退出 )#

delete a
#( 删除对a的所有定义 )#

create b
#( 在目录下创建文件夹b )#

create2 1.txt
#( 在目录下创建文件1.txt )#

cd C:/
#( 进入C:/文件夹 )#

edit 1.txt 123
#( 修改1.txt内容为123 )#

start cmd
#( 启动软件，Windows填文件名或程序名，Android填软件包名 )#

kill cmd
#( 杀进程 )#

send https://www.test.com 1
#( 发送请求到网站 )#

add.gui 1
#( 新建名称为1的GUI界面 )#

open.gui 1
#( 打开GUI界面1 )#

set.gui 1
#( 设置GUI页面内容 )#

reset 100
    print("Hi")
#( 重复执行100次 )#